### PR TITLE
Some changes that should absolutely be tested.

### PR DESCRIPTION
**Pull request by HereInPlainSight**
All my changes should be tested backward and forward, _I do not have a Steam license for XIV_.  Much of this was done blind or by spoofing some directories.
Coming from that situation, I'm not super up to date on the problems / solutions for running XIVLauncher inside of Steam, so I may be missing some obvious things:
- `grep -q "6.3-3"` is used but success message says `Proton 6.3-8`, failure sticks with `-3`.  I'm not currently using 6.3 on anything, so I don't know which is accurate.
- All this checking for Proton 5.0, but it sounds like it only really needs 6.3?  Why check for Proton 5.0?  If you need Proton 6.3, the install command would be `steam "steam://install/1580130"` at the appropriate place instead of `1245040`.

Feel free to take any or none of the changes if it moves things too far out of the scope you want to support.

### CODE REVIEW

**Review by Moosatronic — APPROVED** [review]
Thanks for your help, these are all good improvements.

**Comment by Moosatronic** [comment]
This is also my first published bash script, so I appreciate the help in improvements that I wouldn't have been able to make at least with my current experience.

**Comment by Moosatronic** [comment]
I believe the solution is to use xdg-open as that works with both versions of steam, however I think i'll need to test it.

**Review by Moosatronic — COMMENTED** [review]
I think that xdg-open will work for both flatpak and regular steam, but I am unsure as to how to get xdg-open to open steam as a new process rather than within the terminal, as the user has to end the script to terminate.

**Comment by HereInPlainSight** [comment]
Always glad to help, though I admit that this is my first pull request and somehow I made a mess of things trying to figure out how rebasing works.  My current main repo is diverged by 12 commits from yours, behind by ten... which are the same commits.

I can keep trying to figure this out, or I can close this and push the branch I was working with in the first place that somehow is only two commits ahead of yours and the files look exactly the same as the main branch.

No, I don't know how I managed this.  In either case, besides the rebasing (which I _think_ I had to do just to catch up to the changes, as a merge failed), I switched to using xdg-open instead of calling Steam.  So long as the `steam://` URL is associated with Steam, it should work.

**Comment by Moosatronic** [comment]
yeah the issue i think is that i changed the name of the fix and that has to be resolved. I'm not experienced with git, but i'll try to merge/rebase.

**Comment by Moosatronic** [comment]
k i think i did it?

**Pull request merged**
